name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow when there are pushes to the main branch
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/weyland/stack-discord-bot:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/weyland/stack-discord-bot:latest

      # Optionally, tag the image with the git tag
      - name: Tag Docker image with git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/weyland/stack-discord-bot:latest ghcr.io/weyland/stack-discord-bot:$TAG
          docker push ghcr.io/weyland/stack-discord-bot:$TAG
